apiVersion: v1
kind: Service
metadata:
  name: task7p
  namespace: sit737
spec:
  selector:
    app: sit737_task7p
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer